### ISSUE TITLE
Liens internes

### ISSUE THREAD

**Issue by gallais** [impega/reciptacle#5]
Ça serait pas mal de pouvoir facilement référencer d'autres recettes. On a déjà plusieurs exemples de composants de base (Paneer, Crème pâtissière) qui sont nécessaires pour d'autres recettes du site.

**Comment by hferee** [comment]
C'est déjà le cas pour la recette du panzer je crois. C'est bien ce que tu veux ?

**Comment by gallais** [comment]
Ah mais oui, on peut utiliser un lien markdown normal visant le html généré.
Merci.
